DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `fid` int(11) NOT NULL DEFAULT 0 COMMENT '直属上级ID',
  `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `role_id` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色ID，多个ID以,分隔',
  `phone` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '手机号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色名称',
  `introduce` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '角色介绍',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';

DROP TABLE IF EXISTS `permission`;
CREATE TABLE `permission` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `role_id` VARCHAR(50) NOT NULL DEFAULT 0 COMMENT '角色ID',
  `type` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '权限类型 1 API接口 2 应用程序 3 系统模块',
  `value` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '权限值，随类型变化',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';
